[build]
  command = "pip install -r requirements.txt && cp templates/index.html ./ && waitress-serve --host=0.0.0.0 --port=$PORT app:app"
  publish = "."

[build.environment]
  FLASK_ENV = "production"
